### ISSUE TITLE
Hello Brother, We miss your Work.

### ISSUE THREAD

**Issue by D3WNation** [gato-louco/gato-louco#2]
We Gamers were so happy when we found out that You created something which can help us in such a great way to do what we Gamers are best at. 

The miracle: Exitlag HWID Bypass.exe 

But now its gone and we are so sad to see that we cant play games without lag anymore and when i come back 😔  there is nothing here to help us fix our problem because there is no more Exitlag bypass 🤕.

So my humble request to You, i don't know if i am asking too much but we need You, and you are the Only One who can help us Gamers to do what we are supposed to do. 

Hope you don't mind Gamers getting angery over you coz they dont understand why Hwid Bypass App was removed.

**Comment by Princenirmal** [comment]
Yup we miss you

**Comment by gato-louco** [comment]
Just letting u know that ur giant comment made me create a python script to activate accounts. Check my new project: 
 https://GitHub.com/gato-louco/activate-exitag-accounts

**Comment by gato-louco** [comment]
> Yup we miss you

https://github.com/gato-louco/exitlag-account-activator
